# Generated by Django 4.2.3 on 2023-07-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_id",
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_api.profile",
            ),
        ),
    ]
