# Generated by Django 4.2.3 on 2023-07-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="server_id",
            new_name="server",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="channel_id",
            new_name="channel",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="receiver_id",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="sender_id",
            new_name="sender",
        ),
    ]
