# Generated by Django 4.2.3 on 2023-08-01 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0003_alter_server_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
