# Generated by Django 4.2.3 on 2023-08-06 15:45

import chat_api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0004_messages_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="media",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=chat_api.helpers.generate_image_directory,
            ),
        ),
    ]
