# Generated by Django 4.2.3 on 2023-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0005_alter_messages_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
